### PR TITLE
Pmc merge to proposed_master

### PR DESCRIPTION
**Pull request by dslavineccsl**
Please merge pmc_rebase_to_pm branch to proposed master. 
This branch has clean commits that are  related to pmc changes. Code was tested with FTRN PMC on  scux0095.

### CODE REVIEW

**Comment by alex-cscotg** [comment]
Waiting for @bradomyn

**Comment by bradomyn** [comment]
thanks guys, I'm going to check the pull request within Wed

**Comment by bradomyn** [comment]
done, we have to fix only the commit c24282d0ecca92ec5f294f5f6fc77b56fe2c7d8c and we are done

**Comment by bradomyn** [comment]
this is not nice from github:
"This pull request is closed, but the pmc_rebase_to_pm branch has unmerged commits."

I made a rebase discarding one commit and github complains... the user is not free to merge what he wants??? hummmm, in any case I have rebased and merged and it works, lets see this night in jenkins.

**Pull request closed without merging**
