### PR TITLE
Tempsense merge anjan 13022017

### PR DESCRIPTION
**Pull request by anjan0112**

### CODE REVIEW

**Comment by alex-cscotg** [comment]
Please resolve the conflicts first.

**Comment by anjan0112** [comment]
I have built gateware for all form factors after merging temperature sensor module in my local machine and it works without any issues.

**Comment by alex-cscotg** [comment]
It's fine by me. Waiting for @bradomyn :+1:

**Comment by bradomyn** [comment]
bradomyn is busy today but will take of this in next days!

**Comment by alex-cscotg** [comment]
>> bradomyn is busy today but will take of this in next days!
**>> bradomyn commented on Feb 15**

**Comment by bradomyn** [comment]
Ok

**Comment by bradomyn** [comment]
now to merge

**Comment by alex-cscotg** [comment]
See https://github.com/GSI-CS-CO/bel_projects/pull/41 

#41

**Pull request closed without merging**
